"""empty message

Revision ID: 9f30a79eda2d
Revises: 85a8ba1a4618
Create Date: 2024-05-20 22:50:10.606402

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9f30a79eda2d"
down_revision = "85a8ba1a4618"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.String(length=40), nullable=False),
        sa.Column("investment_id", sa.UUID(), nullable=False),
        sa.Column("date_time", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["investment_id"], ["investments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profits")
    # ### end Alembic commands ###
